/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SizesRouteImport } from './routes/sizes'
import { Route as ResultRouteImport } from './routes/result'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfilesIndexRouteImport } from './routes/profiles/index'
import { Route as ProfilesNewRouteImport } from './routes/profiles/new'
import { Route as ProfilesIdRouteImport } from './routes/profiles/$id'

const SizesRoute = SizesRouteImport.update({
  id: '/sizes',
  path: '/sizes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesIndexRoute = ProfilesIndexRouteImport.update({
  id: '/profiles/',
  path: '/profiles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesNewRoute = ProfilesNewRouteImport.update({
  id: '/profiles/new',
  path: '/profiles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesIdRoute = ProfilesIdRouteImport.update({
  id: '/profiles/$id',
  path: '/profiles/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/history': typeof HistoryRoute
  '/result': typeof ResultRoute
  '/sizes': typeof SizesRoute
  '/profiles/$id': typeof ProfilesIdRoute
  '/profiles/new': typeof ProfilesNewRoute
  '/profiles/': typeof ProfilesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/history': typeof HistoryRoute
  '/result': typeof ResultRoute
  '/sizes': typeof SizesRoute
  '/profiles/$id': typeof ProfilesIdRoute
  '/profiles/new': typeof ProfilesNewRoute
  '/profiles': typeof ProfilesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/history': typeof HistoryRoute
  '/result': typeof ResultRoute
  '/sizes': typeof SizesRoute
  '/profiles/$id': typeof ProfilesIdRoute
  '/profiles/new': typeof ProfilesNewRoute
  '/profiles/': typeof ProfilesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/history'
    | '/result'
    | '/sizes'
    | '/profiles/$id'
    | '/profiles/new'
    | '/profiles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/history'
    | '/result'
    | '/sizes'
    | '/profiles/$id'
    | '/profiles/new'
    | '/profiles'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/history'
    | '/result'
    | '/sizes'
    | '/profiles/$id'
    | '/profiles/new'
    | '/profiles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  HistoryRoute: typeof HistoryRoute
  ResultRoute: typeof ResultRoute
  SizesRoute: typeof SizesRoute
  ProfilesIdRoute: typeof ProfilesIdRoute
  ProfilesNewRoute: typeof ProfilesNewRoute
  ProfilesIndexRoute: typeof ProfilesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sizes': {
      id: '/sizes'
      path: '/sizes'
      fullPath: '/sizes'
      preLoaderRoute: typeof SizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/': {
      id: '/profiles/'
      path: '/profiles'
      fullPath: '/profiles/'
      preLoaderRoute: typeof ProfilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/new': {
      id: '/profiles/new'
      path: '/profiles/new'
      fullPath: '/profiles/new'
      preLoaderRoute: typeof ProfilesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$id': {
      id: '/profiles/$id'
      path: '/profiles/$id'
      fullPath: '/profiles/$id'
      preLoaderRoute: typeof ProfilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  HistoryRoute: HistoryRoute,
  ResultRoute: ResultRoute,
  SizesRoute: SizesRoute,
  ProfilesIdRoute: ProfilesIdRoute,
  ProfilesNewRoute: ProfilesNewRoute,
  ProfilesIndexRoute: ProfilesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
